version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chainsocial-frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8020/api/v1
    depends_on:
      - backend
    restart: unless-stopped

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: chainsocial-admin
    ports:
      - '3000:3000'
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8020/api/v1
      - NEXT_PUBLIC_API_VERSION=v1
      - NEXT_PUBLIC_APP_NAME=ChainSocial Admin
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chainsocial-backend
    ports:
      - '8020:3000'
    environment:
      - PROJECT_VERSION=v1
      - BASE_ENDPOINT_URL=api/
      - DATABASE_URL=postgresql://postgres:chainsocialpass@postgres_db:5432/chainsocialdb?schema=public
      - IS_PRODUCTION=development
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - backend_seed_flag:/usr/src/app/.seed_flags
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: chainsocialdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chainsocialpass
    ports:
      - '5001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  backend_seed_flag: