version: '3.8'

services:
  app:
    build: .
    container_name: soccer-ball-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: soccerballdb
      POSTGRES_USER: soccerballdb
      POSTGRES_PASSWORD: soccerballpass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: